project:
  type: book
  output-dir: docs
  execute-dir: project

book:
  title: "Economics"
  author: "Celâl Güney"
  date: "29/07/2023"
  search: 
    location: sidebar
    type: textbox
  downloads: [pdf, epub]
  navbar:
    left:
      - text: About
        href: https://jeylal.github.io/celalguney/about.html
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: envelope-fill
        href: mailto:celal.gueney@etu.unige.ch
      - text: "Content"
        menu: 
        - text: "Post"
          file: https://jeylal.github.io/celalguney/
        - text: "Economics"
          file: https://jeylal.github.io/heterodox-economics/
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters: 
        - intro.qmd
        - consumer-theory.qmd
        - production-theory.qmd
    - part: "Neoclassical Macroeconomics"
      chapters: 
        - is-lm.qmd
    - part: "Classical-Marxian Models"
      chapters:
        - classical-marxian-models.qmd
    - part: "Neo-Keynesian Models"
      chapters:
        - Neo-keynesian-models.qmd
    - part: "Neo-Kaleckian Models"
      chapters:
        - neo-kaleckian-models.qmd
        - neo-kaleckian-alternative.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      dark: darkly
      light: flatly
  pdf:
    documentclass: scrreprt

editor: visual

