project:
  type: book
  output-dir: docs

book:
  title: "Heterodox Economics"
  author: "Celâl Güney"
  date: "29/07/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - classical-marxian-models.qmd
    - Neo-keynesian-models.qmd
    - neo-kaleckian-models.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      dark: darkly
      light: flatly
  pdf:
    documentclass: scrreprt

editor: visual

